// <auto-generated />
using DataAccess.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.PostgreSql.Migrations
{
    [DbContext(typeof(PostgreApplicationContext))]
    [Migration("20250519132206_added_index_on_fragments")]
    partial class added_index_on_fragments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.GeometryFragment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Fragment")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("GeometryOriginalId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("NonRenderingBorder")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.HasIndex("Fragment");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Fragment"), "GIST");

                    b.HasIndex("GeometryOriginalId");

                    b.ToTable("GeometryFragments");
                });

            modelBuilder.Entity("Entities.GeometryOriginal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Data")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("LayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Data"), "GIST");

                    b.HasIndex("LayerId");

                    b.ToTable("GeometryOriginals");
                });

            modelBuilder.Entity("Entities.Layer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.ToTable("Layers");
                });

            modelBuilder.Entity("Entities.GeometryFragment", b =>
                {
                    b.HasOne("Entities.GeometryOriginal", "GeometryOriginal")
                        .WithMany("GeometryFragments")
                        .HasForeignKey("GeometryOriginalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeometryOriginal");
                });

            modelBuilder.Entity("Entities.GeometryOriginal", b =>
                {
                    b.HasOne("Entities.Layer", "Layer")
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("Entities.GeometryOriginal", b =>
                {
                    b.Navigation("GeometryFragments");
                });
#pragma warning restore 612, 618
        }
    }
}
